# Generated by Django 3.0.8 on 2020-11-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='gender',
            new_name='profile',
        ),
    ]
